version: '3.8'

services:
  scraper-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraper-client-image:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
