version: '3.8'

services:
  scraper-client:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: scraper-client-image:latest
    ports:
      - "${PORT}:${PORT}"
